import 'package:flutter/material.dart';
import "contacts_serializer.dart";
import "styles.dart" as styles;

class AllContactsPage extends StatefulWidget {
  final ContactsSerializer contacts_serializer;
  final void Function(dynamic) open_contact_edit_page;
  final void Function() open_new_contact_page;
  const AllContactsPage(
      {super.key,
      required this.contacts_serializer,
      required this.open_new_contact_page,
      required this.open_contact_edit_page});

  @override
  State<AllContactsPage> createState() {
    return AllContactsPageState();
  }
}

class AllContactsPageState extends State<AllContactsPage> {
  final scroll_controller = ScrollController();

  @override
  void dispose() {
    scroll_controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Padding(
          padding: const EdgeInsets.all(10),
          child: ElevatedButton(
            style: styles.elevated_button_style,
            onPressed: widget.open_new_contact_page,
            child: Padding(
              padding: const EdgeInsets.symmetric(vertical: 10),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                mainAxisSize: MainAxisSize.min,
                children: [
                  Padding(
                    padding: const EdgeInsets.only(top: 3),
                    child: Icon(
                      Icons.add,
                      size: styles.body_text_style.fontSize,
                      color: styles.add_icon_color,
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 10),
                    child: Text(
                      "New Contact",
                      style: styles.body_text_style,
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
        Expanded(
          child: RawScrollbar(
            controller: scroll_controller,
            thumbVisibility: true,
            trackVisibility: true,
            trackColor: styles.contact_container_color,
            thumbColor: styles.contact_container_border_color,
            radius: Radius.circular(10),
            thickness: 10,
            trackRadius: Radius.circular(10),
            child: ScrollConfiguration(
              behavior:
                  ScrollConfiguration.of(context).copyWith(scrollbars: false),
              // used to remove the scrollbar auto-generated by listView below so that the RawScrollbar above can be used for ListView
              child: ListView(
                controller: scroll_controller,
                children: [
                  for (dynamic contact_data
                      in widget.contacts_serializer.contacts_data)
                    UnconstrainedBox(
                      child: Padding(
                        padding: const EdgeInsets.all(10),
                        child: Container(
                          padding: EdgeInsets.symmetric(
                              horizontal: 25, vertical: 10),
                          width: 500,
                          decoration: BoxDecoration(
                              color: styles.contact_container_color,
                              borderRadius: BorderRadius.circular(20),
                              border: Border.all(
                                  width: 3,
                                  color:
                                      styles.contact_container_border_color)),
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                mainAxisSize: MainAxisSize.max,
                                children: [
                                  Text(
                                    "Name : ${contact_data["name"]}",
                                    style: styles.body_text_style,
                                  ),
                                  Text(
                                    "Number : ${contact_data["number"]}",
                                    style: styles.body_text_style,
                                  ),
                                ],
                              ),
                              Expanded(child: SizedBox()),
                              Column(
                                children: [
                                  IconButton(
                                    onPressed: () {
                                      widget
                                          .open_contact_edit_page(contact_data);
                                    },
                                    icon: Icon(Icons.edit),
                                    iconSize: styles.body_text_style.fontSize,
                                    color: styles.edit_icon_color,
                                    hoverColor: styles.icon_button_focus_color,
                                    focusColor: styles.icon_button_focus_color,
                                  ),
                                  IconButton(
                                    onPressed: () {
                                      setState(() {
                                        widget.contacts_serializer
                                            .delete_contact(contact_data["id"]);
                                      });
                                    },
                                    icon: Icon(Icons.delete),
                                    color: styles.delete_icon_color,
                                    iconSize: styles.body_text_style.fontSize,
                                    hoverColor: styles.icon_button_focus_color,
                                    focusColor: styles.icon_button_focus_color,
                                  )
                                ],
                              ),
                            ],
                          ),
                        ),
                      ),
                    )
                ],
              ),
            ),
          ),
        ),
      ],
    );
  }
}
